# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)


class Metadata(google___protobuf___message___Message):
    name = ... # type: typing___Text
    version = ... # type: typing___Text
    language = ... # type: typing___Text
    distribution_name = ... # type: typing___Text
    product_page = ... # type: typing___Text
    github_repository = ... # type: typing___Text
    issue_tracker = ... # type: typing___Text
    stem = ... # type: typing___Text
    serving_path = ... # type: typing___Text

    @property
    def update_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        update_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        name : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        language : typing___Optional[typing___Text] = None,
        distribution_name : typing___Optional[typing___Text] = None,
        product_page : typing___Optional[typing___Text] = None,
        github_repository : typing___Optional[typing___Text] = None,
        issue_tracker : typing___Optional[typing___Text] = None,
        stem : typing___Optional[typing___Text] = None,
        serving_path : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Metadata: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
