# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Metadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    version: typing___Text = ...
    language: typing___Text = ...
    distribution_name: typing___Text = ...
    product_page: typing___Text = ...
    github_repository: typing___Text = ...
    issue_tracker: typing___Text = ...
    stem: typing___Text = ...
    serving_path: typing___Text = ...
    xrefs: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    xref_services: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    @property
    def update_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
    def __init__(
        self,
        *,
        update_time: typing___Optional[
            google___protobuf___timestamp_pb2___Timestamp
        ] = None,
        name: typing___Optional[typing___Text] = None,
        version: typing___Optional[typing___Text] = None,
        language: typing___Optional[typing___Text] = None,
        distribution_name: typing___Optional[typing___Text] = None,
        product_page: typing___Optional[typing___Text] = None,
        github_repository: typing___Optional[typing___Text] = None,
        issue_tracker: typing___Optional[typing___Text] = None,
        stem: typing___Optional[typing___Text] = None,
        serving_path: typing___Optional[typing___Text] = None,
        xrefs: typing___Optional[typing___Iterable[typing___Text]] = None,
        xref_services: typing___Optional[typing___Iterable[typing___Text]] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["update_time", b"update_time"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "distribution_name",
            b"distribution_name",
            "github_repository",
            b"github_repository",
            "issue_tracker",
            b"issue_tracker",
            "language",
            b"language",
            "name",
            b"name",
            "product_page",
            b"product_page",
            "serving_path",
            b"serving_path",
            "stem",
            b"stem",
            "update_time",
            b"update_time",
            "version",
            b"version",
            "xref_services",
            b"xref_services",
            "xrefs",
            b"xrefs",
        ],
    ) -> None: ...

type___Metadata = Metadata
